resources:
- name: stocks
  type: git
  source:
    uri: https://github.com/sanjeevimohan/pcf-attendee-service-code  #<---- REPLACE ME
    branch: concourse_deployment

- name: deploy-attendee-service
  type: cf
  source:
    api: YOUR_PCF_API_ENDPOINT        #<---- REPLACE ME
    username: {{cf-user}}
    password: {{cf-password}}
    organization: YOUR_CI_USER_ORG    #<---- REPLACE ME
    space: YOUR_CI_USER_SPACE         #<---- REPLACE ME
    skip_cert_check: true

jobs:
- name: build
  public: true
  plan:
  - get: attendee-service
  - task: package
    file: attendee-service/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar